"""
Shared pipeline input/output contracts between API and agent pipeline.
"""

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel


class HypothesisResult(BaseModel):
    """
    Structured hypothesis generated by downstream pipeline steps.
    """

    hypothesis_id: str
    description: str
    confidence: Literal["high", "medium", "low", "uncertain", "insufficient_evidence"]
    supporting_evidence: list[str]
    additional_signal_needed: Optional[str] = None


class SimilarCaseResult(BaseModel):
    """
    Structured similar-case retrieval result.
    """

    similar_capsule_id: str
    similarity_score: float
    match_reason: str
    triage_summary: str
    resolution: Optional[str] = None
    confidence: Literal["high", "medium", "low"]


class PipelineInput(BaseModel):
    """
    Single typed pipeline input used by route handlers.
    """

    ticket_id: str
    source_type: str
    source_ref: str
    title: str
    raw_text: str
    event_timestamp: datetime
    agent_id: Optional[str] = None
    scenario_id: Optional[str] = None
    artifacts_ref: Optional[list[str]] = None


class PipelineOutput(BaseModel):
    """
    Single typed pipeline output returned to route handlers.
    """

    capsule_id: str
    triage_summary: str
    hypotheses: list[HypothesisResult]
    similar_cases: list[SimilarCaseResult]
    recommended_steps: list[str]
    pipeline_status: Literal["complete", "partial", "failed"]
    error_message: Optional[str] = None
