"""Stage pipeline for scene description + debate using Cosmos-Reason2 HF inference."""

from __future__ import annotations

import argparse
import json
import os
import re
import uuid
from datetime import datetime, timezone
from typing import Any

import requests

from pipeline.models.handoff_contracts import (
    AnomalyResultRecord,
    DebateInputRecord,
    DebateOutputRecord,
    SceneDescriptionInputRecord,
    SceneDescriptionOutputRecord,
)


def parse_args() -> argparse.Namespace:
    """
    Purpose: Parse CLI options for description + debate stage pipeline.
    Parameters:
        None
    Returns:
        argparse.Namespace: Parsed arguments.
    Called by: main()
    Calls: argparse.ArgumentParser.parse_args()
    """

    parser = argparse.ArgumentParser(
        description="Run scene-description and debate stages with Cosmos-Reason2 HF backend.",
    )
    parser.add_argument(
        "--flagged-jsonl",
        default="outputs/flagged_windows.jsonl",
        help="Anomaly results JSONL input.",
    )
    parser.add_argument(
        "--visual-manifest-jsonl",
        default="outputs/flagged_visuals/manifest.jsonl",
        help="Visual artifact manifest JSONL input.",
    )
    parser.add_argument(
        "--regression-suite-json",
        default="",
        help="Optional JSON file containing regression suite list[str].",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/reasoning",
        help="Output directory for staged artifacts.",
    )
    parser.add_argument(
        "--run-id",
        default="",
        help="Optional run id; autogenerated when omitted.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=20,
        help="Top anomaly-ranked windows to process.",
    )
    parser.add_argument(
        "--only-noise",
        action="store_true",
        help="If set, only process windows flagged as noise.",
    )
    parser.add_argument(
        "--hf-model-id",
        default="",
        help="Optional HF model id override for scene description stage.",
    )
    parser.add_argument(
        "--hf-max-new-tokens",
        type=int,
        default=2400,
        help="Max new tokens for HF backend generation.",
    )
    parser.add_argument(
        "--debate-rounds",
        type=int,
        default=2,
        help="Number of proponent/critic rounds before final judge decision.",
    )
    parser.add_argument(
        "--debate-model-id",
        default="",
        help="Optional NVIDIA NIM text model id override for debate stage.",
    )
    return parser.parse_args()


def _read_jsonl(path: str) -> list[dict[str, Any]]:
    """
    Purpose: Read JSONL rows into memory.
    Parameters:
        path (str): JSONL path.
    Returns:
        list[dict[str, Any]]: Parsed rows.
    Called by: main()
    Calls: open(), json.loads()
    """

    rows: list[dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            rows.append(json.loads(line))
    return rows


def _write_jsonl(path: str, rows: list[dict[str, Any]]) -> None:
    """
    Purpose: Write rows as JSONL to disk.
    Parameters:
        path (str): Output path.
        rows (list[dict[str, Any]]): Rows to write.
    Returns:
        None
    Called by: main()
    Calls: os.makedirs(), json.dumps()
    """

    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row) + "\n")


def _load_regression_suite(path: str) -> list[str]:
    """
    Purpose: Load regression suite list if provided; else return empty list.
    Parameters:
        path (str): JSON path containing list[str].
    Returns:
        list[str]: Loaded suite.
    Called by: main()
    Calls: open(), json.load()
    """

    if not path:
        return []
    with open(path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if isinstance(payload, list):
        return [str(item) for item in payload]
    return []


def _severity_from_outlier(outlier_score: float, is_noise: bool) -> str:
    """
    Purpose: Convert anomaly signals into severity hint for debate stage.
    Parameters:
        outlier_score (float): HDBSCAN outlier score.
        is_noise (bool): Noise flag.
    Returns:
        str: Severity category string.
    Called by: build_debate_input()
    Calls: None
    """

    if is_noise and outlier_score >= 0.25:
        return "critical"
    if outlier_score >= 0.2:
        return "high"
    if outlier_score >= 0.1:
        return "medium"
    return "low"


def _build_description_inputs(
    run_id: str,
    anomaly_rows: list[AnomalyResultRecord],
    manifest_by_window: dict[str, dict[str, Any]],
) -> list[SceneDescriptionInputRecord]:
    """
    Purpose: Build typed description-stage inputs from anomaly + visual artifacts.
    Parameters:
        run_id (str): Current run identifier.
        anomaly_rows (list[AnomalyResultRecord]): Selected anomaly rows.
        manifest_by_window (dict[str, dict[str, Any]]): Visual refs keyed by window_id.
    Returns:
        list[SceneDescriptionInputRecord]: Description-stage inputs.
    Called by: main()
    Calls: SceneDescriptionInputRecord()
    """

    results: list[SceneDescriptionInputRecord] = []
    for row in anomaly_rows:
        manifest = manifest_by_window.get(row.window_id, {})
        media_refs = []
        if manifest.get("grid_path"):
            media_refs.append(str(manifest["grid_path"]))
        if manifest.get("mp4_path"):
            media_refs.append(str(manifest["mp4_path"]))

        description_input = SceneDescriptionInputRecord(
            run_id=run_id,
            window_id=row.window_id,
            scene_token_hex=row.scene_token_hex,
            log_id=row.log_id,
            scenario_tags=row.scenario_tags,
            cluster_label=row.cluster_label,
            is_noise=row.is_noise,
            outlier_score=row.outlier_score,
            anomaly_rank=row.anomaly_rank,
            media_refs=media_refs,
            prompt_context={
                "cluster_label": row.cluster_label,
                "is_noise": row.is_noise,
                "outlier_score": row.outlier_score,
                "anomaly_rank": row.anomaly_rank,
                "quality": row.quality,
                "metadata": row.metadata,
            },
        )
        results.append(description_input)
    return results


def _hf_chat_completion(messages: list[dict[str, Any]]) -> str:
    """
    Purpose: Run local HuggingFace Cosmos-Reason2 chat completion and return text output.
    Parameters:
        messages (list[dict[str, Any]]): Chat messages with role/content pairs.
    Returns:
        str: Generated content text.
    Called by: main(), cosmos_multi_agent_debate()
    Calls: transformers.AutoProcessor.from_pretrained(), model.generate()
    """

    try:
        import torch  # type: ignore[import-not-found]
        import transformers  # type: ignore[import-not-found]
    except Exception as error:  # noqa: BLE001
        raise RuntimeError(
            "HF backend requires transformers and torch installed in the active environment."
        ) from error

    model_id = os.getenv("COSMOS_HF_MODEL_ID", "nvidia/Cosmos-Reason2-8B")
    max_new_tokens = int(os.getenv("COSMOS_HF_MAX_NEW_TOKENS", "2400"))
    video_fps = float(os.getenv("COSMOS_HF_VIDEO_FPS", "8"))
    dtype_name = os.getenv("COSMOS_HF_TORCH_DTYPE", "float16")
    dtype = getattr(torch, dtype_name, torch.float16)

    cache = getattr(_hf_chat_completion, "_cache", None)
    if cache is None or cache.get("model_id") != model_id:
        model = transformers.Qwen3VLForConditionalGeneration.from_pretrained(
            model_id,
            dtype=dtype,
            device_map="auto",
            attn_implementation="sdpa",
            trust_remote_code=True,
        )
        processor = transformers.AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
        cache = {"model_id": model_id, "model": model, "processor": processor}
        setattr(_hf_chat_completion, "_cache", cache)

    model = cache["model"]
    processor = cache["processor"]

    hf_messages: list[dict[str, Any]] = []
    for message in messages:
        content = message.get("content", "")
        normalized_content: list[dict[str, Any]]
        if isinstance(content, list):
            normalized_content = []
            for item in content:
                if not isinstance(item, dict):
                    normalized_content.append({"type": "text", "text": str(item)})
                    continue
                item_type = str(item.get("type", "text")).lower()
                if item_type == "video" and item.get("video"):
                    normalized_content.append(
                        {
                            "type": "video",
                            "video": str(item["video"]),
                            "fps": float(item.get("fps", video_fps)),
                        }
                    )
                elif item_type == "image" and item.get("image"):
                    normalized_content.append(
                        {
                            "type": "image",
                            "image": str(item["image"]),
                        }
                    )
                else:
                    normalized_content.append({"type": "text", "text": str(item.get("text", ""))})
            if not normalized_content:
                normalized_content = [{"type": "text", "text": ""}]
        else:
            normalized_content = [{"type": "text", "text": str(content)}]

        hf_messages.append(
            {
                "role": str(message.get("role", "user")),
                "content": normalized_content,
            }
        )

    inputs = processor.apply_chat_template(
        hf_messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt",
        fps=video_fps,
    )
    inputs = inputs.to(model.device)
    generated_ids = model.generate(**inputs, max_new_tokens=max_new_tokens)
    generated_ids_trimmed = [
        out_ids[len(in_ids):]
        for in_ids, out_ids in zip(inputs.input_ids, generated_ids, strict=False)
    ]
    output_text = processor.batch_decode(
        generated_ids_trimmed,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    )
    return str(output_text[0]).strip() if output_text else ""


def _nim_text_chat_completion(messages: list[dict[str, Any]]) -> str:
    """
    Purpose: Run NVIDIA NIM text chat completion for debate turns.
    Parameters:
        messages (list[dict[str, Any]]): OpenAI-style text messages.
    Returns:
        str: Generated debate response.
    Called by: cosmos_multi_agent_debate()
    Calls: requests.post()
    """

    api_key = os.getenv("NVIDIA_API_KEY", "")
    base_url = os.getenv("NVIDIA_BASE_URL", "https://integrate.api.nvidia.com/v1").rstrip("/")
    model_id = os.getenv("DEBATE_NIM_MODEL_ID", "meta/llama-3.1-8b-instruct")
    temperature = float(os.getenv("DEBATE_TEMPERATURE", "0.2"))

    if not api_key:
        raise RuntimeError(
            "NVIDIA_API_KEY missing for debate stage. Set NVIDIA_API_KEY or use a different debate model path."
        )

    payload = {
        "model": model_id,
        "messages": messages,
        "temperature": temperature,
    }
    response = requests.post(
        f"{base_url}/chat/completions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json=payload,
        timeout=90,
    )
    if response.status_code != 200:
        raise RuntimeError(f"NIM debate call failed: HTTP {response.status_code}: {response.text[:300]}")
    body = response.json()
    return str(body["choices"][0]["message"]["content"]).strip()


def _extract_json_candidates(raw: str) -> list[str]:
    """
    Purpose: Generate likely JSON substrings from model text output.
    Parameters:
        raw (str): Raw model text which may include markdown or extra prose.
    Returns:
        list[str]: Candidate JSON strings ordered by likelihood.
    Called by: _parse_cosmos_description(), _parse_cosmos_debate()
    Calls: re.finditer(), str.find(), str.rfind()
    """

    candidates: list[str] = []
    text = raw.strip()
    if text:
        candidates.append(text)

    # Common model format: ```json { ... } ```
    for match in re.finditer(r"```(?:json)?\s*(.*?)\s*```", raw, flags=re.IGNORECASE | re.DOTALL):
        inner = match.group(1).strip()
        if inner:
            candidates.append(inner)

    # Fallback: take largest brace-delimited region.
    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        candidates.append(raw[start:end + 1].strip())

    # Deduplicate while preserving order.
    seen: set[str] = set()
    unique: list[str] = []
    for candidate in candidates:
        if candidate in seen:
            continue
        seen.add(candidate)
        unique.append(candidate)
    return unique


def _extract_loose_json_string_value(raw: str, key: str) -> str | None:
    """
    Purpose: Extract a JSON string value even when output is truncated/incomplete.
    Parameters:
        raw (str): Raw response text.
        key (str): JSON key to extract.
    Returns:
        str | None: Extracted value or None when key is missing.
    Called by: _parse_cosmos_description()
    Calls: str.find()
    """

    key_marker = f'"{key}"'
    key_index = raw.find(key_marker)
    if key_index == -1:
        return None

    colon_index = raw.find(":", key_index + len(key_marker))
    if colon_index == -1:
        return None

    cursor = colon_index + 1
    while cursor < len(raw) and raw[cursor] in (" ", "\t", "\r", "\n"):
        cursor += 1
    if cursor >= len(raw) or raw[cursor] != '"':
        return None

    cursor += 1
    chunks: list[str] = []
    escaped = False
    while cursor < len(raw):
        char = raw[cursor]
        if escaped:
            chunks.append(char)
            escaped = False
            cursor += 1
            continue
        if char == "\\":
            escaped = True
            cursor += 1
            continue
        if char == '"':
            break
        chunks.append(char)
        cursor += 1

    value = "".join(chunks).strip()
    if not value:
        return None
    return value


def _sanitize_raw_description_fallback(raw: str) -> str:
    """
    Purpose: Remove markdown fence wrappers from raw model output for UI-friendly fallback text.
    Parameters:
        raw (str): Raw model output text.
    Returns:
        str: Sanitized plain text snippet.
    Called by: _parse_cosmos_description()
    Calls: str.replace(), str.startswith(), str.strip()
    """

    text = raw.strip()
    text = text.replace("```json", "").replace("```JSON", "").replace("```", "").strip()
    if text.lower().startswith("json"):
        text = text[4:].strip()
    return text


def _parse_cosmos_description(raw: str) -> dict[str, Any]:
    """
    Purpose: Parse Cosmos description output from strict JSON, fenced JSON, or partial text.
    Parameters:
        raw (str): Raw model output string.
    Returns:
        dict[str, Any]: Normalized keys scene_description, anomaly_rationale, confidence.
    Called by: main()
    Calls: _extract_json_candidates(), json.loads(), re.search()
    """

    for candidate in _extract_json_candidates(raw):
        try:
            parsed = json.loads(candidate)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            continue

    # Partial/invalid JSON fallback: salvage known keys.
    scene_match = re.search(r'"scene_description"\s*:\s*"(.*?)"', raw, flags=re.DOTALL)
    rationale_match = re.search(r'"anomaly_rationale"\s*:\s*"(.*?)"', raw, flags=re.DOTALL)
    confidence_match = re.search(r'"confidence"\s*:\s*"(.*?)"', raw, flags=re.DOTALL)
    loose_scene = _extract_loose_json_string_value(raw, "scene_description")
    loose_rationale = _extract_loose_json_string_value(raw, "anomaly_rationale")
    loose_confidence = _extract_loose_json_string_value(raw, "confidence")

    scene_description = (
        scene_match.group(1)
        if scene_match
        else (loose_scene or _sanitize_raw_description_fallback(raw))
    )
    anomaly_rationale = (
        rationale_match.group(1)
        if rationale_match
        else (
            loose_rationale
            or "Model returned non-JSON or partial JSON description."
        )
    )
    confidence = confidence_match.group(1) if confidence_match else (loose_confidence or "unknown")
    return {
        "scene_description": scene_description,
        "anomaly_rationale": anomaly_rationale,
        "confidence": confidence,
    }


def _parse_cosmos_debate(raw: str) -> dict[str, Any]:
    """
    Purpose: Parse Cosmos debate output from strict JSON, fenced JSON, or partial text.
    Parameters:
        raw (str): Raw model output string.
    Returns:
        dict[str, Any]: Normalized keys decision, recommendation, priority_score, rationale.
    Called by: cosmos_debate()
    Calls: _extract_json_candidates(), json.loads(), re.search()
    """

    for candidate in _extract_json_candidates(raw):
        try:
            parsed = json.loads(candidate)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            continue

    decision_match = re.search(r'"decision"\s*:\s*"(yes|no)"', raw, flags=re.IGNORECASE)
    decision_add_reject_match = re.search(r"\bDECISION\s*:\s*(ADD|REJECT)\b", raw, flags=re.IGNORECASE)
    recommendation_match = re.search(
        r'"recommendation"\s*:\s*"(add_immediately|already_covered|not_critical)"',
        raw,
        flags=re.IGNORECASE,
    )
    recommendation_text_match = re.search(
        r"\bRECOMMENDATION\s*:\s*(ADD_IMMEDIATELY|ALREADY_COVERED|NOT_CRITICAL|ADD|REJECT)\b",
        raw,
        flags=re.IGNORECASE,
    )
    score_match = re.search(r'"priority_score"\s*:\s*([0-9]*\.?[0-9]+)', raw)
    rationale_match = re.search(r'"rationale"\s*:\s*"(.*?)"', raw, flags=re.DOTALL)
    capability_tag_match = re.search(r"\bCAPABILITY_TAG\s*:\s*([^\n\r]+)", raw, flags=re.IGNORECASE)
    decision_value = "no"
    if decision_match:
        decision_value = decision_match.group(1).lower()
    elif decision_add_reject_match:
        decision_value = "yes" if decision_add_reject_match.group(1).lower() == "add" else "no"
    recommendation_value = ""
    if recommendation_match:
        recommendation_value = recommendation_match.group(1).lower()
    elif recommendation_text_match:
        recommendation_token = recommendation_text_match.group(1).lower()
        recommendation_map = {
            "add": "add_immediately",
            "reject": "not_critical",
        }
        recommendation_value = recommendation_map.get(recommendation_token, recommendation_token)
    else:
        # Judge prompts can return DECISION-only text, so infer recommendation from decision.
        recommendation_value = "add_immediately" if decision_value == "yes" else "not_critical"
    return {
        "decision": decision_value,
        "recommendation": recommendation_value,
        "priority_score": float(score_match.group(1)) if score_match else 0.3,
        "rationale": rationale_match.group(1) if rationale_match else raw[:300],
        "capability_tag": capability_tag_match.group(1).strip() if capability_tag_match else "",
    }


def build_debate_input(
    description: SceneDescriptionOutputRecord,
    regression_suite: list[str],
) -> DebateInputRecord:
    """
    Purpose: Convert scene description output to debate input contract row.
    Parameters:
        description (SceneDescriptionOutputRecord): Description-stage output.
        regression_suite (list[str]): Current regression scenarios.
    Returns:
        DebateInputRecord: Typed debate input row.
    Called by: main()
    Calls: DebateInputRecord()
    """

    severity_hint = _severity_from_outlier(
        float(description.metadata.get("outlier_score", 0.0)),
        bool(description.metadata.get("is_noise", False)),
    )
    return DebateInputRecord(
        run_id=description.run_id,
        window_id=description.window_id,
        scene_token_hex=description.scene_token_hex,
        log_id=description.log_id,
        scene_description=description.scene_description,
        anomaly_rationale=description.anomaly_rationale,
        severity_hint=severity_hint,
        regression_suite=regression_suite,
        metadata=description.metadata,
    )


def cosmos_multi_agent_debate(record: DebateInputRecord, rounds: int) -> DebateOutputRecord:
    """
    Purpose: Run multi-round proponent/critic debate with NIM text model, then judge.
    Parameters:
        record (DebateInputRecord): Debate input row.
        rounds (int): Number of proponent/critic rounds.
    Returns:
        DebateOutputRecord: Final decision with transcript metadata.
    Called by: main()
    Calls: _nim_text_chat_completion(), _parse_cosmos_debate()
    """

    rounds = max(1, rounds)
    suite_text = "\n".join([f"{index + 1}. {item}" for index, item in enumerate(record.regression_suite)])
    history: list[str] = []
    latest_proponent = "No proponent argument yet."
    latest_critic = "No critic argument yet."

    for round_index in range(1, rounds + 1):
        proponent_raw = _nim_text_chat_completion(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a safety-critical scenario analyst for an autonomous vehicle "
                        "regression test suite.\n\n"
                        "You have been given an anomaly flagged by the detection pipeline, "
                        "described as:\n"
                        "<scenario>\n"
                        f"{record.scene_description}\n"
                        "</scenario>\n\n"
                        "Your job is to write a PROPOSAL for why this scenario SHOULD be added "
                        "to the regression test suite.\n"
                        "Focus specifically on:\n"
                        "1. What perceptual or behavioral capability does this test?\n"
                        "2. Is this a long-tail or underrepresented event in typical training distributions?\n"
                        "3. What failure mode would go UNDETECTED if this scenario is excluded?\n"
                        "4. Does this scenario expose a coverage gap (occlusions, frame edges, blind spots)?\n\n"
                        "Bias strongly toward inclusion. A false negative is costlier than a false positive.\n"
                        "Output a structured proposal with: "
                        "[Capability Tested], [Failure Mode Exposed], [Coverage Gap], [Severity]."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Round: {round_index}\n\n"
                        f"Window ID: {record.window_id}\n"
                        f"Log ID: {record.log_id}\n"
                        f"Severity hint: {record.severity_hint}\n\n"
                        f"Anomaly rationale:\n{record.anomaly_rationale}\n\n"
                        f"Existing regression suite:\n{suite_text}\n\n"
                        f"Latest critic argument:\n{latest_critic}"
                    ),
                },
            ]
        )
        latest_proponent = proponent_raw.strip()
        history.append(f"Round {round_index} - Proponent: {latest_proponent}")

        critic_raw = _nim_text_chat_completion(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a regression test suite quality controller. Your job is to challenge "
                        "proposals and prevent test suite bloat from low-signal entries.\n\n"
                        "Challenge the proposal on these axes:\n"
                        "1. REDUNDANCY: Is this already covered by an existing or close semantic test?\n"
                        "2. REPRODUCIBILITY: Can it be reliably reproduced in simulation?\n"
                        "3. SIGNAL QUALITY: Genuine blind spot or sensor/data artifact?\n"
                        "4. ACTIONABILITY: If model fails, is there a concrete retraining/architecture fix?\n\n"
                        "IMPORTANT CONSTRAINT: Do NOT argue against inclusion solely due to rarity.\n"
                        "Only reject with concrete failures on the axes above."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Round: {round_index}\n\n"
                        "You have been given a proposal to add the following scenario:\n"
                        "<proposal>\n"
                        f"{latest_proponent}\n"
                        "</proposal>\n\n"
                        f"Scenario description:\n{record.scene_description}\n\n"
                        f"Existing regression suite:\n{suite_text}"
                    ),
                },
            ]
        )
        latest_critic = critic_raw.strip()
        history.append(f"Round {round_index} - Critic: {latest_critic}")

    judge_raw = _nim_text_chat_completion(
        messages=[
            {
                "role": "system",
                "content": (
                    "You are the final arbiter for an autonomous vehicle regression test suite.\n\n"
                    "Decision framework:\n"
                    "- ADD if the scenario tests a capability that could fail silently, represents "
                    "underrepresented deployment events, and critique does not show concrete quality failure.\n"
                    "- REJECT only if critique demonstrates artifact, strong redundancy, or irreproducibility.\n"
                    "Tie-break rule: when uncertain, ADD.\n\n"
                    "Output format:\n"
                    "DECISION: [ADD | REJECT]\n"
                    "RATIONALE: <one paragraph>\n"
                    "CAPABILITY_TAG: <tag>"
                ),
            },
            {
                "role": "user",
                "content": (
                    "You have received:\n"
                    f"- A scenario anomaly: <scenario>{record.scene_description}</scenario>\n"
                    f"- A proposal for inclusion: <proposal>{latest_proponent}</proposal>\n"
                    f"- A critical challenge: <critique>{latest_critic}</critique>\n\n"
                    f"Existing regression suite:\n{suite_text}\n\n"
                    "Full debate transcript:\n"
                    + "\n".join(history)
                ),
            },
        ]
    )
    parsed = _parse_cosmos_debate(judge_raw)
    decision = "yes" if str(parsed.get("decision", "no")).lower() == "yes" else "no"
    recommendation = str(parsed.get("recommendation", "")).strip().lower()
    if recommendation not in {"add_immediately", "already_covered", "not_critical"}:
        recommendation = "add_immediately" if decision == "yes" else "not_critical"
    priority_score = max(0.0, min(1.0, float(parsed.get("priority_score", 0.3))))
    enriched_metadata = dict(record.metadata)
    enriched_metadata.update(
        {
            "debate_mode": "multi_agent",
            "debate_model_id": os.getenv("DEBATE_NIM_MODEL_ID", "meta/llama-3.1-8b-instruct"),
            "debate_rounds": rounds,
            "debate_history": history,
            "judge_raw_output": judge_raw,
            "capability_tag": str(parsed.get("capability_tag", "")).strip(),
        }
    )
    return DebateOutputRecord(
        run_id=record.run_id,
        window_id=record.window_id,
        scene_token_hex=record.scene_token_hex,
        log_id=record.log_id,
        decision=decision,
        recommendation=recommendation,
        priority_score=priority_score,
        rationale=str(parsed.get("rationale", "No rationale provided.")),
        model_source="nim_text_debate_model",
        metadata=enriched_metadata,
    )


def main() -> int:
    """
    Purpose: Execute Cosmos HF description stage + cheaper NIM text debate stage.
    Parameters:
        None
    Returns:
        int: Exit status code.
    Called by: CLI entrypoint
    Calls: parse_args(), _build_description_inputs(), cosmos stage functions
    """

    args = parse_args()
    run_id = args.run_id or f"run_{uuid.uuid4().hex[:8]}"
    os.environ["COSMOS_HF_MAX_NEW_TOKENS"] = str(args.hf_max_new_tokens)
    if args.hf_model_id:
        os.environ["COSMOS_HF_MODEL_ID"] = args.hf_model_id
    if args.debate_model_id:
        os.environ["DEBATE_NIM_MODEL_ID"] = args.debate_model_id

    anomaly_raw = _read_jsonl(args.flagged_jsonl)
    anomaly_rows = [AnomalyResultRecord.model_validate(row) for row in anomaly_raw]
    if args.only_noise:
        anomaly_rows = [row for row in anomaly_rows if row.is_noise]
    anomaly_rows = sorted(anomaly_rows, key=lambda row: row.anomaly_rank)[: args.top_k]
    if not anomaly_rows:
        print("No anomaly rows selected for description/debate stages.")
        return 1

    manifest_by_window: dict[str, dict[str, Any]] = {}
    if os.path.isfile(args.visual_manifest_jsonl):
        for row in _read_jsonl(args.visual_manifest_jsonl):
            manifest_by_window[str(row.get("window_id", ""))] = row

    regression_suite = _load_regression_suite(args.regression_suite_json)
    description_inputs = _build_description_inputs(
        run_id=run_id,
        anomaly_rows=anomaly_rows,
        manifest_by_window=manifest_by_window,
    )

    description_prompt = (
    "You are an expert autonomous driving perception and scene-understanding model. "
    "Analyze this dashcam video clip frame by frame and reason carefully before responding.\n\n"

    "<think>\n"
    "Work through the following in order before writing your final answer:\n"
    "1. Establish the static scene: road geometry, lane count, intersection type, "
    "   signage, barriers, surface conditions, lighting, weather.\n"
    "2. Identify all dynamic actors: label each (e.g., Vehicle-1, Pedestrian-A) and "
    "   track their trajectory, speed estimate, and heading across the clip.\n"
    "3. Identify the ego vehicle's motion: speed, lane position, steering inputs.\n"
    "4. Reconstruct a strict temporal log at ~8 fps (t=0.000s, t=0.125s, t=0.250s …) "
    "   noting state changes for every tracked actor.\n"
    "5. Flag any anomalies: near-misses, right-of-way violations, sudden stops, "
    "   unexpected trajectories, occluded actors, or sensor-edge-case conditions.\n"
    "6. Assign an anomaly confidence score and justify it.\n"
    "</think>\n\n"

    "After your reasoning, return STRICT JSON only (no markdown, no preamble) with:\n"
    "{\n"
    '  "scene_description": "<rich temporal narrative referencing t= timestamps>",\n'
    '  "road_layout": {\n'
    '    "type": "<intersection|highway|urban-street|parking-lot|…>",\n'
    '    "lanes": <int>,\n'
    '    "surface": "<dry|wet|snow|…>",\n'
    '    "lighting": "<daylight|dusk|night|artificial>"\n'
    '  },\n'
    '  "actors": [\n'
    '    {"id": "Vehicle-1", "type": "sedan", "trajectory": "…", "notable_behavior": "…"}\n'
    '  ],\n'
    '  "temporal_log": [\n'
    '    {"t": 0.000, "event": "…"},\n'
    '    {"t": 0.125, "event": "…"}\n'
    '  ],\n'
    '  "anomaly_rationale": "<what happened, why it is anomalous, what risk it poses>",\n'
    '  "anomaly_type": "<none|near-miss|violation|erratic-motion|occlusion|other>",\n'
    '  "confidence": "low|medium|high"\n'
    "}"
)
    description_outputs: list[SceneDescriptionOutputRecord] = []
    for record in description_inputs:
        try:
            user_payload = {
                "window_id": record.window_id,
                "scene_token_hex": record.scene_token_hex,
                "log_id": record.log_id,
                "scenario_tags": record.scenario_tags,
                "cluster_label": record.cluster_label,
                "is_noise": record.is_noise,
                "outlier_score": record.outlier_score,
                "anomaly_rank": record.anomaly_rank,
                "media_refs": record.media_refs,
            }

            media_blocks: list[dict[str, Any]] = []
            for media_ref in record.media_refs:
                abs_path = os.path.abspath(media_ref)
                lowered = media_ref.lower()
                if lowered.endswith((".mp4", ".mov", ".mkv", ".avi")):
                    media_blocks.append({"type": "video", "video": abs_path, "fps": 8})
                elif lowered.endswith((".png", ".jpg", ".jpeg", ".webp")):
                    media_blocks.append({"type": "image", "image": abs_path})
            media_blocks.append({"type": "text", "text": json.dumps(user_payload)})

            raw_description = _hf_chat_completion(
                messages=[
                    {"role": "system", "content": description_prompt},
                    {"role": "user", "content": media_blocks},
                ]
            )
            parsed = _parse_cosmos_description(raw_description)
            scene_description_text = str(
                parsed.get("scene_description", "No description available.")
            ).strip()
            anomaly_rationale_text = str(parsed.get("anomaly_rationale", "")).strip()
            if not anomaly_rationale_text:
                anomaly_rationale_text = (
                    "Rationale inferred from anomaly signals: "
                    f"cluster_label={record.cluster_label}, "
                    f"is_noise={record.is_noise}, "
                    f"outlier_score={record.outlier_score:.4f}, "
                    f"anomaly_rank={record.anomaly_rank}. "
                    "Model did not provide explicit anomaly_rationale field; "
                    "manual review should confirm whether observed actor interactions, "
                    "right-of-way behavior, or motion trajectories are risk-relevant."
                )
            description_outputs.append(
                SceneDescriptionOutputRecord(
                    run_id=record.run_id,
                    window_id=record.window_id,
                    scene_token_hex=record.scene_token_hex,
                    log_id=record.log_id,
                    scene_description=scene_description_text,
                    anomaly_rationale=anomaly_rationale_text,
                    confidence=str(parsed.get("confidence", "unknown")),
                    model_source="cosmos_reason2",
                    media_refs=record.media_refs,
                    metadata=record.prompt_context,
                )
            )
        except Exception as error:  # noqa: BLE001
            print(f"COSMOS_BLOCKED: true during description stage: {error}")
            return 1

    debate_inputs: list[DebateInputRecord] = [
        build_debate_input(record, regression_suite) for record in description_outputs
    ]
    debate_outputs: list[DebateOutputRecord] = []
    for record in debate_inputs:
        try:
            debate_outputs.append(cosmos_multi_agent_debate(record, args.debate_rounds))
        except Exception as error:  # noqa: BLE001
            print(f"COSMOS_BLOCKED: true during debate stage: {error}")
            return 1

    os.makedirs(args.output_dir, exist_ok=True)
    description_inputs_path = os.path.join(args.output_dir, "description_inputs.jsonl")
    description_outputs_path = os.path.join(args.output_dir, "description_outputs.jsonl")
    debate_inputs_path = os.path.join(args.output_dir, "debate_inputs.jsonl")
    debate_outputs_path = os.path.join(args.output_dir, "debate_outputs.jsonl")

    _write_jsonl(
        description_inputs_path,
        [row.model_dump() for row in description_inputs],
    )
    _write_jsonl(
        description_outputs_path,
        [row.model_dump() for row in description_outputs],
    )
    _write_jsonl(
        debate_inputs_path,
        [row.model_dump() for row in debate_inputs],
    )
    _write_jsonl(
        debate_outputs_path,
        [row.model_dump() for row in debate_outputs],
    )

    summary = {
        "run_id": run_id,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "selected_rows": len(anomaly_rows),
        "cosmos_blocked": False,
        "description_backend": "hf_cosmos_reason2",
        "debate_backend": "nim_text",
        "debate_model_id": os.getenv("DEBATE_NIM_MODEL_ID", "meta/llama-3.1-8b-instruct"),
        "description_inputs": description_inputs_path,
        "description_outputs": description_outputs_path,
        "debate_inputs": debate_inputs_path,
        "debate_outputs": debate_outputs_path,
    }
    summary_path = os.path.join(args.output_dir, "summary.json")
    with open(summary_path, "w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2)

    print("COSMOS_BLOCKED: false (Cosmos path succeeded).")
    print(f"Saved summary: {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
